# Generated by Django 5.2.1 on 2025-05-30 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_apellidos_alter_persona_edad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
