# Generated by Django 5.2.1 on 2025-05-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_rename_nombres_persona_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='donador',
            field=models.BooleanField(default=False),
        ),
    ]
