# Generated by Django 5.2.1 on 2025-05-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_persona_donador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='donador',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
