# Generated by Django 5.2.1 on 2025-06-05 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_alter_persona_apellidos_alter_persona_donador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
